name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: lipu-app/webappanalyzer-data
        path: tests/webappanalyzer-data

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-${{ hashFiles('Cargo.toml') }}

    - name: cargo fetch
      run: cargo fetch

    - name: cargo test
      run: RUST_BACKTRACE=1 cargo test --release -- --include-ignored
